version: "3"
services:
  proxy:
    image: envoyproxy/envoy:v1.15.0
    ports:
      - 8080:51051
    volumes:
      - ./envoy-proxy.yaml:/etc/envoy/envoy.yaml
    depends_on:
      - grpc_chat_backend

  grpc_chat_backend:
    build:
      context: .
      dockerfile: Dockerfile_backend

  grpc_chat_frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - 3000:80