FROM node:16.10-alpine as build

WORKDIR /app

COPY web/package.json /app
COPY web/package-lock.json /app

# install and cache dependencies
RUN npm install

COPY web /app

#build the project for production
RUN npm run build

FROM nginx:1.25.3-alpine3.18
# copy the build folder from react to the root of nginx (www)
COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
# replace with custom one
COPY web/deployments/nginx.conf /etc/nginx/conf.d
# --------- /only for those using react router ----------
# expose port 80 to the outer world
EXPOSE 80
# start nginx
CMD ["nginx", "-g", "daemon off;"]